# Generated by Django 4.1.6 on 2023-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
